export type CleanerSemanticThemeTokens = {
  safe: string;
  safeSurface: string;
  safeBorder: string;
  safeText: string;
  safeIcon: string;
  safeContrast: string;
  blocked: string;
  blockedSurface: string;
  blockedBorder: string;
  blockedText: string;
  blockedIcon: string;
  blockedContrast: string;
  conditional: string;
  conditionalSurface: string;
  conditionalBorder: string;
  conditionalText: string;
  conditionalIcon: string;
  conditionalContrast: string;
  danger: string;
  dangerSurface: string;
  dangerBorder: string;
  dangerText: string;
  dangerIcon: string;
  dangerContrast: string;
  review: string;
  reviewSurface: string;
  reviewBorder: string;
  reviewText: string;
  reviewIcon: string;
  reviewContrast: string;
  excluded: string;
  excludedSurface: string;
  excludedBorder: string;
  excludedText: string;
  excludedIcon: string;
  excludedContrast: string;
  recovery: string;
  recoverySurface: string;
  recoveryBorder: string;
  recoveryText: string;
  recoveryContrast: string;
};

export const CLEANER_SEMANTIC_TOKENS_BY_MODE = {
  light: {
    safe: "#197443ff",
    safeSurface: "#e8f6edff",
    safeBorder: "#65aa7fff",
    safeText: "#0c5a32ff",
    safeIcon: "#197443ff",
    safeContrast: "#ffffffff",
    blocked: "#9a6700ff",
    blockedSurface: "#fff5d6ff",
    blockedBorder: "#d2a32aff",
    blockedText: "#694600ff",
    blockedIcon: "#916000ff",
    blockedContrast: "#ffffffff",
    conditional: "#b94f0aff",
    conditionalSurface: "#fff0e5ff",
    conditionalBorder: "#df884aff",
    conditionalText: "#873800ff",
    conditionalIcon: "#ad4808ff",
    conditionalContrast: "#ffffffff",
    danger: "#ae2935ff",
    dangerSurface: "#fdebedff",
    dangerBorder: "#d76770ff",
    dangerText: "#811923ff",
    dangerIcon: "#ae2935ff",
    dangerContrast: "#ffffffff",
    review: "#5a47adff",
    reviewSurface: "#f0edffff",
    reviewBorder: "#9385d1ff",
    reviewText: "#433389ff",
    reviewIcon: "#5a47adff",
    reviewContrast: "#ffffffff",
    excluded: "#62666cff",
    excludedSurface: "#eff0f1ff",
    excludedBorder: "#a6a9adff",
    excludedText: "#4a4e53ff",
    excludedIcon: "#62666cff",
    excludedContrast: "#ffffffff",
    recovery: "#126b3aff",
    recoverySurface: "#ddf5e6ff",
    recoveryBorder: "#4da970ff",
    recoveryText: "#084c28ff",
    recoveryContrast: "#ffffffff",
  },
  dark: {
    safe: "#57c982ff",
    safeSurface: "#142e20ff",
    safeBorder: "#347e51ff",
    safeText: "#c9f7d9ff",
    safeIcon: "#6edc96ff",
    safeContrast: "#071a0fff",
    blocked: "#e6b94fff",
    blockedSurface: "#332909ff",
    blockedBorder: "#8d6c17ff",
    blockedText: "#ffe9a1ff",
    blockedIcon: "#f2c95fff",
    blockedContrast: "#211800ff",
    conditional: "#f39a55ff",
    conditionalSurface: "#3a2112ff",
    conditionalBorder: "#9a5427ff",
    conditionalText: "#ffd2b3ff",
    conditionalIcon: "#ffab69ff",
    conditionalContrast: "#201006ff",
    danger: "#ef707bff",
    dangerSurface: "#38181cff",
    dangerBorder: "#933b44ff",
    dangerText: "#ffc6ccff",
    dangerIcon: "#ff818bff",
    dangerContrast: "#25080cff",
    review: "#a894f0ff",
    reviewSurface: "#24203dff",
    reviewBorder: "#6557a0ff",
    reviewText: "#e1d9ffff",
    reviewIcon: "#b5a2ffff",
    reviewContrast: "#171026ff",
    excluded: "#8e9399ff",
    excludedSurface: "#242628ff",
    excludedBorder: "#53575cff",
    excludedText: "#d0d3d6ff",
    excludedIcon: "#a6abb0ff",
    excludedContrast: "#111315ff",
    recovery: "#54d184ff",
    recoverySurface: "#10341fff",
    recoveryBorder: "#338958ff",
    recoveryText: "#d6ffe4ff",
    recoveryContrast: "#06180dff",
  },
} as const satisfies Record<"light" | "dark", CleanerSemanticThemeTokens>;
